name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: prepare environment
      run: |
        brew install ldid make
        echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV
        echo "PATH=/usr/local/opt/make/libexec/gnubin:$PATH" >> $GITHUB_ENV
        
    
    - name: verify updated cache
      id: verify-cache
      run: |
        echo "::set-output name=heads::`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/xybp888/iOS-SDKs | head -n 1 | cut -f 1`"
    - name: use cache
      id: cache
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/theos
        key: ${{ runner.os }}-${{ steps.verify-cache.outputs.heads }}

    - name: get theos
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: 'theos'
        repository: theos/theos

    - name: get sdks
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        path: 'theos/sdks'
        repository: xybp888/iOS-SDKs
    - name: actual build
      run: |
        rm -f packages/*
        make package FINALPACKAGE=1
    - name: upload deb
      uses: actions/upload-artifact@v2.2.0
      with:
        name: 'Package'
        path: ${{ github.workspace }}/packages/*.deb